#!/bin/bash

# Remove existing local_manifests
rm -rf .repo/local_manifests/

# Initialize git lfs
git lfs install

# Initialize the manifest
repo init --no-repo-verify --git-lfs --depth=1 -u https://github.com/Trijal08/mistifest.git -b 15
echo "====================="
echo "= Repo init success ="
echo "====================="

# Clone local manifests
git clone --depth=1 https://github.com/Trijal08/local_manifests.git -b Mist_OS-15.0-k6.1-shusky .repo/local_manifests
echo "================================="
echo "= Local manifests clone success ="
echo "================================="

# Sync repositories (now let that sync in)
/opt/crave/resync.sh || curl -sSf https://raw.githubusercontent.com/Trijal08/build_scripts/refs/heads/sync_script/resync.sh | bash
echo "================"
echo "= Sync success ="
echo "================"

# Directory setup
rm -rf vendor/mist/overlays/SettingsHuskyOverlay
rm -rf vendor/addons/prebuilt/product/priv-app/BCR
cat > vendor/gms/common/Android.bp << EOF
// Automatically generated file. DO NOT MODIFY
//
// This file is generated by vendor/gms/setup-makefiles.sh

soong_namespace {
	imports: [
	],
}

android_app_import {
	name: "GoogleExtShared",
	owner: "gms",
	apk: "proprietary/system/app/GoogleExtShared/GoogleExtShared.apk",
	overrides: ["ExtShared"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
}

android_app_import {
	name: "GooglePrintRecommendationService",
	owner: "gms",
	apk: "proprietary/system/app/GooglePrintRecommendationService/GooglePrintRecommendationService.apk",
	overrides: ["PrintRecommendationService"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
}

android_app_import {
	name: "DocumentsUIGoogle",
	owner: "gms",
	apk: "proprietary/system/priv-app/DocumentsUIGoogle/DocumentsUIGoogle.apk",
	overrides: ["DocumentsUI"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
}

android_app_import {
	name: "TagGoogle",
	owner: "gms",
	apk: "proprietary/system/priv-app/TagGoogle/TagGoogle.apk",
	overrides: ["Tag"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
}

android_app_import {
	name: "CalculatorGooglePrebuilt_85005407",
	owner: "gms",
	apk: "proprietary/product/app/CalculatorGooglePrebuilt_85005407/CalculatorGooglePrebuilt_85005407.apk",
	overrides: ["ExactCalculator"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "CalendarGooglePrebuilt",
	owner: "gms",
	apk: "proprietary/product/app/CalendarGooglePrebuilt/CalendarGooglePrebuilt.apk",
	overrides: ["Calendar2", "Calendar", "Etar"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "DevicePolicyPrebuilt-v10052480",
	owner: "gms",
	apk: "proprietary/product/app/DevicePolicyPrebuilt-v10052480/DevicePolicyPrebuilt-v10052480.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "GoogleContacts",
	owner: "gms",
	apk: "proprietary/product/app/GoogleContacts/GoogleContacts.apk",
	overrides: ["Contacts", "Contacts2"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "GoogleTTS",
	owner: "gms",
	apk: "proprietary/product/app/GoogleTTS/GoogleTTS.apk",
	overrides: ["PicoTts"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "LatinIMEGooglePrebuilt",
	owner: "gms",
	apk: "proprietary/product/app/LatinIMEGooglePrebuilt/LatinIMEGooglePrebuilt.apk",
	overrides: ["LatinIME"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "LocationHistoryPrebuilt",
	owner: "gms",
	apk: "proprietary/product/app/LocationHistoryPrebuilt/LocationHistoryPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "MarkupGoogle_v2",
	owner: "gms",
	apk: "proprietary/product/app/MarkupGoogle_v2/MarkupGoogle_v2.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "NgaResources",
	owner: "gms",
	apk: "proprietary/product/app/NgaResources/NgaResources.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "Photos",
	owner: "gms",
	apk: "proprietary/product/app/Photos/Photos.apk",
	overrides: ["Gallery2"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "PixelThemesStub",
	owner: "gms",
	apk: "proprietary/product/app/PixelThemesStub/PixelThemesStub.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "PrebuiltDeskClockGoogle_76004981",
	owner: "gms",
	apk: "proprietary/product/app/PrebuiltDeskClockGoogle_76004981/PrebuiltDeskClockGoogle_76004981.apk",
	overrides: ["DeskClock"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "PrebuiltGoogleTelemetryTvp",
	owner: "gms",
	apk: "proprietary/product/app/PrebuiltGoogleTelemetryTvp/PrebuiltGoogleTelemetryTvp.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "SoundAmplifierPrebuilt_v4.7.638126989",
	owner: "gms",
	apk: "proprietary/product/app/SoundAmplifierPrebuilt_v4.7.638126989/SoundAmplifierPrebuilt_v4.7.638126989.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "SwitchAccessPrebuilt_1.15.0.629986523",
	owner: "gms",
	apk: "proprietary/product/app/SwitchAccessPrebuilt_1.15.0.629986523/SwitchAccessPrebuilt_1.15.0.629986523.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "VoiceAccessPrebuilt",
	owner: "gms",
	apk: "proprietary/product/app/VoiceAccessPrebuilt/VoiceAccessPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "WallpaperEmojiPrebuilt-v470",
	owner: "gms",
	apk: "proprietary/product/app/WallpaperEmojiPrebuilt-v470/WallpaperEmojiPrebuilt-v470.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "arcore-1.42",
	owner: "gms",
	apk: "proprietary/product/app/arcore-1.42/arcore-1.42.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

android_app_import {
	name: "talkback",
	owner: "gms",
	apk: "proprietary/product/app/talkback/talkback.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	product_specific: true,
}

//android_app_import {
//	name: "AICorePrebuilt",
//	owner: "gms",
//	apk: "proprietary/product/priv-app/AICorePrebuilt/AICorePrebuilt.apk",
//	preprocessed: true,
//	presigned: true,
//	dex_preopt: {
//		enabled: false,
//	},
//	privileged: true,
//	product_specific: true,
//}

android_app_import {
	name: "AmbientStreaming",
	owner: "gms",
	apk: "proprietary/product/priv-app/AmbientStreaming/AmbientStreaming.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "AndroidAutoStubPrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/AndroidAutoStubPrebuilt/AndroidAutoStubPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "ConfigUpdater",
	owner: "gms",
	apk: "proprietary/product/priv-app/ConfigUpdater/ConfigUpdater.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "DeviceIntelligenceNetworkPrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/DeviceIntelligenceNetworkPrebuilt/DeviceIntelligenceNetworkPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "FilesPrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/FilesPrebuilt/FilesPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "GoogleCamera",
	owner: "gms",
	apk: "proprietary/product/priv-app/GoogleCamera/GoogleCamera.apk",
	overrides: ["Aperture"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "GoogleDialer",
	owner: "gms",
	apk: "proprietary/product/priv-app/GoogleDialer/GoogleDialer.apk",
	overrides: ["Dialer"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "GoogleOneTimeInitializer",
	owner: "gms",
	apk: "proprietary/product/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk",
	overrides: ["OneTimeInitializer"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "GoogleRestorePrebuilt-v526684",
	owner: "gms",
	apk: "proprietary/product/priv-app/GoogleRestorePrebuilt-v526684/GoogleRestorePrebuilt-v526684.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PartnerSetupPrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/PartnerSetupPrebuilt/PartnerSetupPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "Phonesky",
	owner: "gms",
	apk: "proprietary/product/priv-app/Phonesky/Phonesky.apk",
	overrides: ["messaging"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PrebuiltBugle",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltBugle/PrebuiltBugle.apk",
	overrides: ["messaging"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PrebuiltGmsCoreVic",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/PrebuiltGmsCoreVic.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PrebuiltGmsCoreVic_AdsDynamite.uncompressed",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/app_chimera/m/PrebuiltGmsCoreVic_AdsDynamite.uncompressed.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PrebuiltGmsCoreVic_CronetDynamite.uncompressed",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/app_chimera/m/PrebuiltGmsCoreVic_CronetDynamite.uncompressed.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PrebuiltGmsCoreVic_DynamiteLoader.uncompressed",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/app_chimera/m/PrebuiltGmsCoreVic_DynamiteLoader.uncompressed.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PrebuiltGmsCoreVic_DynamiteModulesA.uncompressed",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/app_chimera/m/PrebuiltGmsCoreVic_DynamiteModulesA.uncompressed.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PrebuiltGmsCoreVic_DynamiteModulesC.uncompressed",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/app_chimera/m/PrebuiltGmsCoreVic_DynamiteModulesC.uncompressed.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PrebuiltGmsCoreVic_GoogleCertificates.uncompressed",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/app_chimera/m/PrebuiltGmsCoreVic_GoogleCertificates.uncompressed.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PrebuiltGmsCoreVic_MapsDynamite.uncompressed",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/app_chimera/m/PrebuiltGmsCoreVic_MapsDynamite.uncompressed.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "PrebuiltGmsCoreVic_MeasurementDynamite.uncompressed",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/app_chimera/m/PrebuiltGmsCoreVic_MeasurementDynamite.uncompressed.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "AndroidPlatformServices",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/m/independent/AndroidPlatformServices.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "MlkitBarcodeUIPrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/m/optional/MlkitBarcodeUIPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "VisionBarcodePrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/PrebuiltGmsCore/m/optional/VisionBarcodePrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "SafetyHubPrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/SafetyHubPrebuilt/SafetyHubPrebuilt.apk",
	overrides: ["EmergencyInfo"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "ScribePrebuilt_v7.0.633113815",
	owner: "gms",
	apk: "proprietary/product/priv-app/ScribePrebuilt_v7.0.633113815/ScribePrebuilt_v7.0.633113815.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "SearchSelectorPrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/SearchSelectorPrebuilt/SearchSelectorPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "SettingsIntelligenceGooglePrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/SettingsIntelligenceGooglePrebuilt/SettingsIntelligenceGooglePrebuilt.apk",
	overrides: ["SettingsIntelligence"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "SetupWizardPrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/SetupWizardPrebuilt/SetupWizardPrebuilt.apk",
	overrides: ["Provision"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "Velvet",
	owner: "gms",
	apk: "proprietary/product/priv-app/Velvet/Velvet.apk",
	overrides: ["QuickSearchBox"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "WallpaperEffect",
	owner: "gms",
	apk: "proprietary/product/priv-app/WallpaperEffect/WallpaperEffect.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "WeatherPixelPrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/WeatherPixelPrebuilt/WeatherPixelPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "WellbeingPrebuilt",
	owner: "gms",
	apk: "proprietary/product/priv-app/WellbeingPrebuilt/WellbeingPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}

android_app_import {
	name: "AccessibilityMenu",
	owner: "gms",
	apk: "proprietary/system_ext/app/AccessibilityMenu/AccessibilityMenu.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	system_ext_specific: true,
}

android_app_import {
	name: "EmergencyInfoGoogleNoUi",
	owner: "gms",
	apk: "proprietary/system_ext/app/EmergencyInfoGoogleNoUi/EmergencyInfoGoogleNoUi.apk",
	certificate: "platform",
	dex_preopt: {
		enabled: false,
	},
	system_ext_specific: true,
}

android_app_import {
	name: "GoogleFeedback",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/GoogleFeedback/GoogleFeedback.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "GoogleServicesFramework",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "NexusLauncherRelease",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/NexusLauncherRelease/NexusLauncherRelease.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "SetupWizardPixelPrebuilt",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/SetupWizardPixelPrebuilt/SetupWizardPixelPrebuilt.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "StorageManagerGoogle",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/StorageManagerGoogle/StorageManagerGoogle.apk",
	overrides: ["StorageManager"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "SystemUIClocks-BigNum",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/SystemUIClocks-BigNum/SystemUIClocks-BigNum.apk",
	certificate: "platform",
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "SystemUIClocks-Calligraphy",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/SystemUIClocks-Calligraphy/SystemUIClocks-Calligraphy.apk",
	certificate: "platform",
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "SystemUIClocks-Flex",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/SystemUIClocks-Flex/SystemUIClocks-Flex.apk",
	certificate: "platform",
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "SystemUIClocks-Growth",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/SystemUIClocks-Growth/SystemUIClocks-Growth.apk",
	certificate: "platform",
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "SystemUIClocks-Inflate",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/SystemUIClocks-Inflate/SystemUIClocks-Inflate.apk",
	certificate: "platform",
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "SystemUIClocks-Metro",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/SystemUIClocks-Metro/SystemUIClocks-Metro.apk",
	certificate: "platform",
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "SystemUIClocks-NumOverlap",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/SystemUIClocks-NumOverlap/SystemUIClocks-NumOverlap.apk",
	certificate: "platform",
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "SystemUIClocks-Weather",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/SystemUIClocks-Weather/SystemUIClocks-Weather.apk",
	certificate: "platform",
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

android_app_import {
	name: "WallpaperPickerGoogleRelease",
	owner: "gms",
	apk: "proprietary/system_ext/priv-app/WallpaperPickerGoogleRelease/WallpaperPickerGoogleRelease.apk",
	overrides: ["ThemePicker", "WallpaperPicker2", "WallpaperPicker", "WallpaperCropper"],
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	system_ext_specific: true,
}

dex_import {
	name: "com.google.android.dialer.support",
	owner: "gms",
	jars: ["proprietary/product/framework/com.google.android.dialer.support.jar"],
	product_specific: true,
}

android_app_import {
	name: "DevicePersonalizationPrebuiltPixel2020",
	owner: "gms",
	apk: "proprietary/product/priv-app/DevicePersonalizationPrebuiltPixel2020/DevicePersonalizationPrebuiltPixel2020.apk",
	preprocessed: true,
	presigned: true,
	dex_preopt: {
		enabled: false,
	},
	privileged: true,
	product_specific: true,
}
EOF

# Auto-sign build
if [ ! -d vendor/lineage-priv ]; then
   curl -sSf https://raw.githubusercontent.com/Trijal08/crDroid-build-signed-script-auto/main/create-signed-env.sh | bash
fi

# Export some info about us
export BUILD_USERNAME="GamerBoy1234294 • Misty Fresh"
export BUILD_HOSTNAME="crave"
export BUILD_BROKEN_MISSING_REQUIRED_MODULES=true
echo "==============="
echo "= Export Done ="
echo "==============="

# Set up build environment
source build/envsetup.sh
croot
echo "================="
echo "= Envsetup Done ="
echo "================="

# Lunch and build the ROM
make installclean -j$(nproc --all)
mistify husky
mist b
mist fb
mistify shiba
mist b
mist fb
